- name: install nodejs and npm
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - nodejs
    - npm
- name: install forever package
  npm: name=forever state=present global=yes
- name: create nodejs path
  file: 
    path: /var/nodejs
    state: directory

- name: copy project directory
  copy:
    src: nodejs/good_reads
    dest: /var/nodejs/good_reads

- name: Running NPM install
  npm:
     path: /var/nodejs/good_reads/good_reads/
  changed_when: false
  notify: install express

- name: check running nodejs application
  command: forever list
  register: forever_list
  changed_when: false

- name: start nodejs app
  command: forever start /var/nodejs/good_reads/good_reads/index.js
  when: " forever_list.stdout.find('/var/nodejs/good_reads/good_reads/index.js') == -1"
