- name: download nodejs 8 repo
  shell: "curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -"

- name: install nodejs and npm
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - nodejs
- name: install forever package
  npm: name=forever state=present global=yes
- name: create nodejs path
  file: 
    path: /var/nodejs
    state: directory

- name: copy project directory
  copy:
    src: nodejs/good_reads
    dest: /var/nodejs/good_reads

- name: Running NPM install
  command: npm install /var/nodejs/good_reads/good_reads/
  changed_when: false

- name: install express
  command: npm install express --save
  changed_when: false

- name: check running nodejs application
  command: forever list
  register: forever_list
  changed_when: false

- name: start nodejs app
  command: forever start /var/nodejs/good_reads/good_reads/index.js
  when: " forever_list.stdout.find('/var/nodejs/good_reads/good_reads/index.js') == -1"
