- name: install nodejs and npm
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - nodejs
    - npm
- name: install forever package
  npm: name=forever state=present global=yes
- name: create nodejs path
  file: 
    path: /var/nodejs
    state: directory

- name: copy project directory
  copy:
    src: ../files/nodejs/goodreads
    dest: /var/nodejs/goodreads

- name: Running NPM install
  npm: path=/var/nodejs/goodreads/goodreads/
  changed_when: false

- name: check running nodejs application
  command: forever list
  register: forever_list
  changed_when: false

- name: start nodejs app
  command: forever start /var/nodejs/goodreads/goodreads/index.js
  when: " forever_list.stdout.find('/var/nodejs/goodreads/goodreads/index.js') == -1"
