---

- name: create angular path
  file: 
    path: /var/angular
    state: directory

- name: copy project directory
  copy:
    src: goodReads
    dest: /var/angular/good_reads

- name: connecting angular with nodejs
  copy:
    src: baseurl.ts
    dest: /var/angular/good_reads/goodreads/src/app/shared/baseurl.ts
