---
- name: configure app server
  hosts: nodejs
  become: true
  roles:
    - nodejs
  handlers:
    - name: install express
      npm:
        name: "{{item}}"
        path: /var/nodejs/goodreads/goodreads/
      with_items:
             - express
             - mongoose

